### ISSUE TITLE
Can Today date be unavailable past certain hour?

### ISSUE THREAD

**Issue by cjlaborde** [joffreyBerrier/vue-hotel-datepicker#35]
Is there a way to not allow to make reservations starting on the same day?
For example, makes no sense to allow user to make reservation at 10 pm today.

Basically Gray today date if the current time is past 4 pm
airbnb does something similar.

Perhaps it's possible and I am not aware how to.

**Comment by joffreyBerrier** [comment]
Do you mean blocking today's date from a certain time?

If yes, you can do it on your own by adding today's date in the table of `disabledDates` like this:

``` javascript
currentDate = new Date()
currentHour = currentDate.getHours()
hourToBloked = 16

if (currentHour >= hourToBloked) {
  this.disabledDates.push(currentDate)
}
```

**Comment by cjlaborde** [comment]
Thank you for code, it works great!

**Comment by joffreyBerrier** [comment]
No problem, do not hesitate, if you have any suggestions or ameliorations
