### ISSUE TITLE
how can I pass date to Calendar?

### ISSUE THREAD

**Issue by cjlaborde** [joffreyBerrier/vue-hotel-datepicker#46]
how can I pass date to DatePicker?

Basically to pass date to date picker and had it show the date.
Since I will do the selection with fullcalendar.
https://fullcalendar.io/docs/date-clicking-selecting-demo

So I select date here and take the start date and end date values and pass it to vue hotel datepicker and had it show the date.
Here image of what I want to do.
https://i.imgur.com/TmZEb25.png

**Comment by joffreyBerrier** [comment]
Hi @cjlaborde your message is confuse

If you want to add a startDate and endDate, you can pass the props `startingDateValue` and `endingDateValue` to the component

**Comment by cjlaborde** [comment]
Thank you so much worst great!
