### ISSUE TITLE
v4.0.0-dev in krystalcampioni/vue-hotel-datepicker incorporates all the changes

### ISSUE THREAD

**Issue by matiasperrone** [joffreyBerrier/vue-hotel-datepicker#72]
https://github.com/krystalcampioni/vue-hotel-datepicker/releases/tag/v4.0.0-dev

**Comment by matiasperrone** [comment]
https://github.com/krystalcampioni/vue-hotel-datepicker v4.1 is now live!

**Comment by joffreyBerrier** [comment]
@matiasperrone 
Your v-4.1 is just a copy of my code with new naming html class so I don't need thx
